# apiVersion: v1
# kind: Secret
# metadata:
#   name: secrets
# data:

#   github-access-token: ==== base64 encoded credential ====

#   auth0-domain: ==== base64 encoded credential ====
#   auth0-audience: ==== base64 encoded credential ====
#   auth0-client-id: ==== base64 encoded credential ====

#   auth0-mapi-audience: ==== base64 encoded credential ====
#   auth0-m2m-client: ==== base64 encoded credential ====
#   auth0-m2m-secret: ==== base64 encoded credential ====

#   aws-s3-bucket: ==== base64 encoded credential ====
#   aws-cognito-identity: ==== base64 encoded credential ====

#   freshbooks-client-id: ==== base64 encoded credential ====
#   freshbooks-client-secret: ==== base64 encoded credential ====

#   sendgrid-api-key: ==== base64 encoded credential ====

#   view-db-identity-host: ==== base64 encoded credential ====
#   view-db-identity-database-name: ==== base64 encoded credential ====
#   view-db-identity-username: ==== base64 encoded credential ====
#   view-db-identity-password: ==== base64 encoded credential ====
#   view-db-identity-url: ==== base64 encoded credential ====

#   mic-db-identity-host: ==== base64 encoded credential ====
#   mic-db-identity-database-name: ==== base64 encoded credential ====
#   mic-db-identity-username: ==== base64 encoded credential ====
#   mic-db-identity-password: ==== base64 encoded credential ====
#   mic-db-identity-url: ==== base64 encoded credential ====

#   mic-db-projects-host: ==== base64 encoded credential ====
#   mic-db-projects-database-name: ==== base64 encoded credential ====
#   mic-db-projects-username: ==== base64 encoded credential ====
#   mic-db-projects-password: ==== base64 encoded credential ====
#   mic-db-projects-url: ==== base64 encoded credential ====

#   msg-db-nats-host: ==== base64 encoded credential ====
#   msg-db-nats-database-name: ==== base64 encoded credential ====
#   msg-db-nats-username: ==== base64 encoded credential ====
#   msg-db-nats-password: ==== base64 encoded credential ====
#   msg-db-nats-port: ==== base64 encoded credential ====
#   msg-db-nats-url: ==== base64 encoded credential ====

