name: publish-app-identity

on:
  push:
    paths:
      - ".github/workflows/publish-app-identity.yml"
      - "identity/application/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        env:
          OWNER: ${{ github.repository_owner }}
          IMAGE: app-identity
        run: |
          export SHA=$(git rev-parse --short HEAD)

          docker build ./identity/application --tag ghcr.io/$OWNER/$IMAGE:$SHA
          docker push ghcr.io/$OWNER/$IMAGE:$SHA

          echo $OWNER/$IMAGE:$SHA > .build-version

          cat > patch.sh <<EOF
          #!/bin/bash
          sed -i 's/$IMAGE:.*/$IMAGE:$SHA/' $IMAGE-depl.yaml
          EOF

          chmod +x patch.sh

      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/devpie-infra
          token: ${{ secrets.PAT }}
          path: devpie-infra
      - run: |
          export IMAGE=$(cat .build-version)

          mv patch.sh devpie-infra/manifests
          cd devpie-infra/manifests

          ./patch.sh
          rm patch.sh

          git config --local user.email github-actions@github.com
          git config --local user.name github-actions
          git add .
          git commit -m "new release: $IMAGE"
          git push
